# Generated by Django 3.2.3 on 2021-06-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
