# Generated by Django 3.2.3 on 2021-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
    ]
