# Generated by Django 3.2.3 on 2021-06-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-created',), 'verbose_name': 'Рассылки', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
