# Generated by Django 3.2.3 on 2021-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210602_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoes',
            field=models.BooleanField(default=True),
        ),
    ]
