# Generated by Django 3.2.3 on 2021-06-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_shoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoes',
            field=models.BooleanField(default=False),
        ),
    ]
