# Generated by Django 3.2.3 on 2021-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_shoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size_shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_shoes', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoes',
        ),
        migrations.AddField(
            model_name='product',
            name='size_shoes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='catalog.Size_shoes'),
        ),
    ]
