# Generated by Django 3.2.3 on 2021-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210602_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ManyToManyField(related_name='sizes', to='catalog.Category'),
        ),
    ]
