# Generated by Django 3.2.3 on 2021-06-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0015_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesCatrgory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Категории для одежды',
                'verbose_name_plural': 'Категории для одежды',
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('size_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.size')),
            ],
            options={
                'verbose_name': 'Размеры для одежды',
                'verbose_name_plural': 'Размеры для одежды',
            },
            bases=('catalog.size',),
        ),
        migrations.CreateModel(
            name='ShoesCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Категории для обуви',
                'verbose_name_plural': 'Категории для обуви',
            },
            bases=('catalog.category',),
        ),
        migrations.CreateModel(
            name='ShoesSize',
            fields=[
                ('size_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.size')),
            ],
            options={
                'verbose_name': 'Размеры для обуви',
                'verbose_name_plural': 'Размеры для обуви',
            },
            bases=('catalog.size',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_catalog.category_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_catalog.product_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.shoescategory')),
                ('sizes', models.ManyToManyField(related_name='products', to='catalog.ShoesSize')),
            ],
            options={
                'verbose_name': 'Обувь',
                'verbose_name_plural': 'Обувь',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.clothescatrgory')),
                ('sizes', models.ManyToManyField(related_name='products', to='catalog.ClothesSize')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
            bases=('catalog.product',),
        ),
    ]
