# Generated by Django 3.2.3 on 2021-06-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210606_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterModelOptions(
            name='clothescatrgory',
            options={'verbose_name': 'Clothes Categories', 'verbose_name_plural': 'Clothes Categories'},
        ),
        migrations.AlterModelOptions(
            name='clothessize',
            options={'verbose_name': 'Clothes Sizes', 'verbose_name_plural': 'Clothes Sizes'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Shoes', 'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='shoescategory',
            options={'verbose_name': 'Shoes Categories', 'verbose_name_plural': 'Shoes Categories'},
        ),
        migrations.AlterModelOptions(
            name='shoessize',
            options={'verbose_name': 'Shoes Sizes', 'verbose_name_plural': 'Shoes Sizes'},
        ),
    ]
