# Generated by Django 3.2.3 on 2021-06-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210607_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterModelOptions(
            name='clothescatrgory',
            options={'verbose_name': 'Категории одежды', 'verbose_name_plural': 'Категории одежды'},
        ),
        migrations.AlterModelOptions(
            name='clothessize',
            options={'verbose_name': 'Размеры одежды', 'verbose_name_plural': 'Размеры одежды'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name': 'Обувь', 'verbose_name_plural': 'Обувь'},
        ),
        migrations.AlterModelOptions(
            name='shoescategory',
            options={'verbose_name': 'Категории обуви', 'verbose_name_plural': 'Категории обуви'},
        ),
        migrations.AlterModelOptions(
            name='shoessize',
            options={'verbose_name': 'Размеры обуви', 'verbose_name_plural': 'размеры обуви'},
        ),
    ]
