# Generated by Django 3.2.3 on 2021-06-19 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mart', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('index', models.CharField(max_length=6)),
                ('mart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.mart')),
            ],
        ),
    ]
