# Generated by Django 3.2.3 on 2021-06-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210619_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.promo'),
            preserve_default=False,
        ),
    ]
